# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lap_f <- function(x) {
    .Call('_StatComp20052_lap_f', PACKAGE = 'StatComp20052', x)
}

rw_MetropolisC <- function(sigma, x0, N) {
    .Call('_StatComp20052_rw_MetropolisC', PACKAGE = 'StatComp20052', sigma, x0, N)
}

